# -*- mode: python -*-

from waflib import Context
libshit_cross = getattr(Context.g_module, 'LIBSHIT_CROSS', False)

def options(ctx):
    ctx.system_opt('brigand', cross=libshit_cross)
    ctx.system_opt('doctest', cross=libshit_cross)

    ctx.recurse('.', name='options', wscript='wscript_boost', once=False)
    ctx.recurse('.', name='options', wscript='wscript_libcxx', once=False)
    ctx.recurse('.', name='options', wscript='wscript_lua', once=False)

def configure(ctx):
    # start with libcxx, other c++ libs depend on it
    ctx.recurse('.', name='configure', wscript='wscript_libcxx', once=False)

    def system_brigand(ctx):
        ctx.check_cfg(package='libbrigand', args='--cflags',
                      uselib_store='BRIGAND',
                      define_name='', add_have_to_env=False)
    ctx.with_chk(
        'brigand', {'system': system_brigand, 'bundle': 'brigand/include'},
        cross=libshit_cross)

    def system_doctest(ctx):
        ctx.check_cxx(header_name='doctest.h', uselib_store='DOCTEST',
                      define_name='')
    def doctest_post(ctx):
        if ctx.env.WITH_TESTS: # will be false with host variant
            defs = ['LIBSHIT_WITH_TESTS=1']
        else:
            defs = ['LIBSHIT_WITH_TESTS=0']
        ctx.env.append_value('DEFINES_DOCTEST', defs)
    ctx.with_chk(
        'doctest', {'system': system_doctest, 'bundle': 'doctest/doctest'},
        cross=libshit_cross, post_chk=doctest_post)

    ctx.recurse('.', name='configure', wscript='wscript_boost', once=False)
    ctx.recurse('.', name='configure', wscript='wscript_lua', once=False)

def build(ctx):
    ctx.recurse('.', name='build', wscript='wscript_boost', once=False)
    ctx.recurse('.', name='build', wscript='wscript_libcxx', once=False)
    ctx.recurse('.', name='build', wscript='wscript_lua', once=False)
